apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: rajeshpalle/nodeapp-test:tv1 # Replace with your Docker image name
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "postgresql"  # Replace with your PostgreSQL service name
            - name: DB_USER
              value: "cG9zdGdyZXM="  # Replace with your PostgreSQL username
            - name: DB_PASSWORD
              value: "cGFzc3dvcmQ="  # Replace with your PostgreSQL password
            - name: DB_NAME
              value: "bXlkYg=="  # Replace with your PostgreSQL database name
