apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=          # base64 encoded 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=      # base64 encoded 'password'
  POSTGRES_DB: bXlkYg==               # base64 encoded 'mydb'
